import type { RegionalStore } from "@/types";

export function generateRegionalStores(): RegionalStore[] {
  return [
    {
      id: "store-001",
      name: "Koramangala",
      openTasks: 4,
      rupeesAtRiskPerHour: 2840,
      completionRate7d: 0.82,
      phantomRate: 0.12,
      cameraCoverage: 0.91,
    },
    {
      id: "store-002",
      name: "Indiranagar",
      openTasks: 2,
      rupeesAtRiskPerHour: 1120,
      completionRate7d: 0.78,
      phantomRate: 0.15,
      cameraCoverage: 0.88,
    },
    {
      id: "store-003",
      name: "Whitefield",
      openTasks: 6,
      rupeesAtRiskPerHour: 3560,
      completionRate7d: 0.71,
      phantomRate: 0.18,
      cameraCoverage: 0.85,
    },
    {
      id: "store-004",
      name: "HSR Layout",
      openTasks: 3,
      rupeesAtRiskPerHour: 1890,
      completionRate7d: 0.65,
      phantomRate: 0.21,
      cameraCoverage: 0.82,
    },
    {
      id: "store-005",
      name: "Jayanagar",
      openTasks: 5,
      rupeesAtRiskPerHour: 2340,
      completionRate7d: 0.58,
      phantomRate: 0.24,
      cameraCoverage: 0.79,
    },
    {
      id: "store-006",
      name: "Malleshwaram",
      openTasks: 1,
      rupeesAtRiskPerHour: 680,
      completionRate7d: 0.52,
      phantomRate: 0.28,
      cameraCoverage: 0.76,
    },
    {
      id: "store-007",
      name: "Electronic City",
      openTasks: 7,
      rupeesAtRiskPerHour: 4120,
      completionRate7d: 0.45,
      phantomRate: 0.31,
      cameraCoverage: 0.73,
    },
    {
      id: "store-008",
      name: "Marathahalli",
      openTasks: 3,
      rupeesAtRiskPerHour: 1560,
      completionRate7d: 0.38,
      phantomRate: 0.35,
      cameraCoverage: 0.7,
    },
    {
      id: "store-009",
      name: "Bellandur",
      openTasks: 8,
      rupeesAtRiskPerHour: 4890,
      completionRate7d: 0.32,
      phantomRate: 0.38,
      cameraCoverage: 0.68,
    },
    {
      id: "store-010",
      name: "Yelahanka",
      openTasks: 2,
      rupeesAtRiskPerHour: 920,
      completionRate7d: 0.28,
      phantomRate: 0.42,
      cameraCoverage: 0.65,
    },
    {
      id: "store-011",
      name: "Banashankari",
      openTasks: 4,
      rupeesAtRiskPerHour: 1780,
      completionRate7d: 0.22,
      phantomRate: 0.45,
      cameraCoverage: 0.62,
    },
    {
      id: "store-012",
      name: "Hebbal",
      openTasks: 9,
      rupeesAtRiskPerHour: 5240,
      completionRate7d: 0.14,
      phantomRate: 0.52,
      cameraCoverage: 0.58,
    },
  ];
}
